server:
  port: 7362
spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: http://localhost:8023
          predicates:
            - Path=/api/**

# 开启日志方便查看
#logging:
#  level:
#    org:
#      springframework:
#        cloud:
#          gateway: trace
dubbo:
  application:
    name: dubbo-api-consumer
    logger: slf4j
  protocol:
    name: dubbo
    port: -1
  registry:
    timeout: 5000
    address: nacos://36.133.31.228:8848